# object detector boot.py
# generated by maixhub.com

import sensor, image, lcd, time
import KPU as kpu
import gc, sys

from fpioa_manager import fm

fm.register(9, fm.fpioa.UART1_TX, force=True)
fm.register(10, fm.fpioa.UART1_RX, force=True)

from machine import UART

uart_A = UART(UART.UART1, 115200, 8, 1, 0, timeout=1000, read_buf_len=4096)

def lcd_show_except(e):
    import uio
    err_str = uio.StringIO()
    sys.print_exception(e, err_str)
    err_str = err_str.getvalue()
    img = image.Image(size=(224,224))
    img.draw_string(0, 10, err_str, scale=1, color=(0xff,0x00,0x00))
    lcd.display(img)

def main(anchors, labels = None, model_addr="/sd/m.kmodel", sensor_window=(224, 224), lcd_rotation=3, sensor_hmirror=True, sensor_vflip=False):
    sensor.reset()
    sensor.set_pixformat(sensor.RGB565)
    sensor.set_framesize(sensor.QVGA)
    sensor.set_windowing(sensor_window)
    sensor.set_hmirror(sensor_hmirror)
    sensor.set_vflip(sensor_vflip)
    sensor.run(1)

    red_threshold   = (0,   80,  10,   70,   -0,   30)
    black_threshold = (0, 35,-10,10,-10,10 )
    lcd.init(type=1)
    lcd.rotation(lcd_rotation)
    lcd.clear(lcd.WHITE)

    if not labels:
        with open('labels.txt','r') as f:
            exec(f.read())
    if not labels:
        print("no labels.txt")
        img = image.Image(size=(320, 240))
        img.draw_string(90, 110, "no labels.txt", color=(255, 0, 0), scale=2)
        lcd.display(img)
        return 1
    try:
        img = image.Image("startup.jpg")
        lcd.display(img)
    except Exception:
        img = image.Image(size=(320, 240))
        img.draw_string(90, 110, "loading model...", color=(255, 255, 255), scale=2)
        lcd.display(img)

    try:
        task = None
        task = kpu.load(model_addr)
        kpu.init_yolo2(task, 0.5, 0.01, 5, anchors) # threshold:[0,1], nms_value: [0, 1]
        flag="0"
        count=0
        while count < 50:
            img = sensor.snapshot()
            t = time.ticks_ms()
            objects = kpu.run_yolo2(task, img)
            if objects:
                for obj in objects:
                    pos = obj.rect()
                    img.draw_rectangle(pos)
                    img.draw_string(pos[0], pos[1], "%s : %.2df" %(labels[obj.classid()], obj.value()), scale=2, color=(255, 0, 0))
                    if labels[obj.classid()] == flag :
                        count = count+1
                    else :count=1
                    flag = labels[obj.classid()]
                    img.draw_string((0,0,str(count)),scale=3,color=(255,0,0))
                    lcd.display(img)
                    print(count)
        if labels[obj.classid()] == "1":
            uart_A.write("1")
        elif labels[obj.classid()] == "2":
            uart_A.write("2")
        else :
            uart_A.write("m")
        while(True):
            img = sensor.snapshot()
            t = time.ticks_ms()
            blobs_r = img.find_blobs([red_threshold],roi=(0,70,224,80))
            if blobs_r:
                for b in blobs_r:
                    if b.area()>5000:
                        objects = kpu.run_yolo2(task, img)
                        print(objects)
                        t = time.ticks_ms() - t
                        if objects:
                            for obj in objects:
                                pos = obj.rect()
                                img.draw_rectangle(pos)
                                img.draw_string(pos[0], pos[1], "%s : %.2df" %(labels[obj.classid()], obj.value()), scale=2, color=(255, 0, 0))
                        uart_A.write('c')
                        print('c')
                        while uart_A.any():
                              time.sleep_ms(1)
                              read_data = uart_A.read()
                              print(read_data)
                              time.sleep_ms(1)

            pass
            blobs_b = img.find_blobs([black_threshold],roi=(0,0,224,224),area_threshold=1000)
            if blobs_b:
                for b in blobs_b:
                    tmp=img.draw_rectangle(b[0:4])
                    tmp=img.draw_cross(b[5], b[6])
                    objects = kpu.run_yolo2(task, img)
                    print(objects)
                    if objects:
                        for obj in objects:
                            pos = obj.rect()
                            img.draw_rectangle(pos)
                            img.draw_string(pos[0], pos[1], "%s : %.2df" %(labels[obj.classid()], obj.value()), scale=2, color=(255, 0, 0))
            if  len(blobs_r+blobs_b) == 0:
                uart_A.write("s")
                print("s")
            img.draw_string(0, 200, "t:%dms" %(t), scale=2, color=(255, 0, 0))
            img.draw_string(0, 140, str(flag), scale=2, color=(255, 0, 0))
            lcd.display(img)
    except Exception as e:
        raise e
    finally:
        if not task is None:
            kpu.deinit(task)


if __name__ == "__main__":
    try:
        labels =  ["0", "9", "1", "3", "4", "5", "6", "7", "8", "2"]
        #labels = ["1","4","5","2","3","6","7","1","8","6"]
        anchors = [1.6807, 2.3961, 1.7407, 1.8191, 1.9408, 2.9951, 2.1292, 2.1292, 2.4596, 2.4682]
        #anchors = [0.8990825414657592, 1.1265289783477783, 2.3038991689682007, 4.136850118637085, 2.2209479808807373, 3.2270641326904297, 1.6964831948280334, 2.6169722080230713, 2.285168170928955, 2.386849880218506]
        # main(anchors = anchors, labels=labels, model_addr=0x300000, lcd_rotation=0)
        main(anchors = anchors, labels=labels, model_addr="/sd/m.kmodel")
    except Exception as e:
        sys.print_exception(e)
        lcd_show_except(e)
    finally:
        gc.collect()
